apiVersion: 1
contactPoints:
    - orgId: 1
      name: Email
      receivers:
        - uid: be7ivz8w493whd
          type: email
          settings:
            addresses: $GRAFANA_ALERT_RECEIVER_EMAIL
            singleEmail: false
          disableResolveMessage: false

groups:
    - orgId: 1
      name: 1m
      folder: dashboards
      interval: 1m
      rules:
        - uid: ee7iw6a2h9ce8f
          title: CPU Usage
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ce6cbza2345j4f
          panelId: 4
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ce6cbza2345j4f
            __panelId__: "4"
            description: CPU usage is above 80% for the last 5 minutes.
            summary: High CPU usage detected
          isPaused: false
          notification_settings:
            receiver: Email
        - uid: de7iwkz64zegwa
          title: High Memory Usage
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: |
                    (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 75
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ce6cbza2345j4f
          panelId: 5
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ce6cbza2345j4f
            __panelId__: "5"
            description: Memory usage is above 75% on for the last 5 minutes.
            summary: High memory usage detected
          isPaused: false
          notification_settings:
            receiver: Email
