admin:
  existingSecret: grafana-admin-secret
dashboardsProvider:
  enabled: true
  configMaps:
    default: basic-metrics-dashboard
dashboardsConfigMaps:
   - configMapName: basic-metrics-dashboard
     fileName: dashboard_layout.json
datasources:
  secretName: datasource-secret
