admin:
  existingSecret: grafana-admin-secret
datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://127.0.0.1:50870
        version: 1
        editable: true
        isDefault: true
#      - name: Alertmanager
#        uid: alertmanager
#        type: alertmanager
#        access: proxy
#        orgId: 1
#        url: http://prometheus-alertmanager.monitoring.svc.cluster.local:9093
#        version: 1
#        editable: true