name: Install Software
run-name: Installing Software to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run-software-installation:
        description: "Run Software Installation (k3s, helm, prometheus)? (yes/no)"
        required: true
        type: choice
        options:
          - "yes"
          - "no"
        default: "no"

permissions:
  id-token: write   # This is required for requesting the JWT

jobs:
  install:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run-software-installation == 'yes' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run script on EC2
        run: ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.AWS_EC2_PUBLIC_IP }} 'bash -s' < install_tools.sh
