name: Install Software
run-name: Installing Software to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run-software-installation:
        description: "Run Software Installation (k3s, helm, prometheus)? (yes/no)"
        required: true
        type: choice
        options:
          - "yes"
          - "no"
        default: "no"

permissions:
  id-token: write   # This is required for requesting the JWT

jobs:
  install:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run-software-installation == 'yes' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEPLOY }}/GithubActionsRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run software installation script
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=i-0abcd1234efgh5678" \
            --document-name "AWS-RunInstallSoftwareScript" \
            --comment "Running install software script via GHA" \
            --parameters '{"commands":["bash install_tools.sh"]}' \
            --output text

